[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx prisma db push && node dist/utils/seed.js && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
